apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "coredns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "coredns.labels" . | nindent 4 }}
data:
  Corefile: |-
    . {
        errors
        log
        ready
        health {
           lameduck 5s
        }
        prometheus :9153
        template IN SRV {
            match "(?P<name>.cscf)?\.ims\.mnc\d{2,3}\.mcc\d{3}\.3gppnetwork.org"
            answer "{{`{{ .Name }} 1D SRV 0 0 5060 ims-{{ or .Group.name \"icscf\" }}`}}.{{ Release.Namespace }}.svc.cluster.local"
            fallthrough
        }
        template IN ANY {
            match "(^|[.])(?P<name>[^.]*).*\.mnc\d{2,3}\.mcc\d{3}\.3gppnetwork.org"
            answer "{{`{{ .Name }} 1D IN CNAME ims-{{ .Group.name }}`}}.{{ Release.Namespace }}.svc.cluster.local"
            fallthrough
        }
        forward . /etc/resolv.conf
        loop
        reload
        loadbalance
    }
