services:
  ocs:
    image: ghcr.io/lyatanski/cgrates
    configs:
    - source: cgrates.json
      target: /etc/cgrates/cgrates.json
    expose:
    - 3868/tcp


configs:
  cgrates.json:
    content: |
      {
          "general": {
              "logger": "*stdout",
              "log_level": 7,
          },
          "data_db": {
              "db_type": "*internal",
          },
          "stor_db": {
              "db_type": "*internal",
          },
          "rals": {
              "enabled": true,
          },
          "schedulers": {
              "enabled": true,
          },
          "cdrs": {
              "enabled": true,
          },
          "attributes": {
              "enabled": true,
          },
          "chargers": {
              "enabled": true,
          },
          "sessions": {
              "enabled": true,
              "attributes_conns": ["*localhost"],
              "chargers_conns": ["*localhost"],
              "rals_conns": ["*localhost"],
              "cdrs_conns": ["*localhost"],
          },
          "apiers": {
              "enabled": true,
              "caches_conns":["*localhost"],
          },
          "diameter_agent": {
              "enabled": true,
              "listen": "0.0.0.0:3868",
              "listen_net": "tcp",
              "origin_host": "ocs.${REALM}",
              "origin_realm": "${REALM}",
              "request_processors": [
                  {
                      "id": "VoiceInit",
                      "filters": [
                          "*string:~*vars.*cmd:CCR",
                      ],
                      "flags": [
                          "*initiate",
                          "*accounts",
                          "*attributes",
                          "*continue"
                      ],
                      "request_fields": [
                          {
                              "tag": "ToR",
                              "path": "*cgreq.ToR",
                              "type": "*constant",
                              "value": "*voice"
                          },
                          {
                              "tag": "OriginID",
                              "path": "*cgreq.OriginID",
                              "type": "*variable",
                              "value": "~*req.Session-Id",
                              "mandatory": true
                          },
                          {
                              "tag": "RequestType",
                              "path": "*cgreq.RequestType",
                              "type": "*constant",
                              "value": "*prepaid"
                          },
                          {
                              "tag": "Category",
                              "path": "*cgreq.Category",
                              "type": "*constant",
                              "value": "call"
                          },
                          {
                              "tag": "Account",
                              "path": "*cgreq.Account",
                              "type": "*constant",
                              "value": "~*req.Subscription-Id.Subscription-Id-Data",
                          },
                          {
                              "tag": "Destination",
                              "path": "*cgreq.Destination",
                              "type": "*variable",
                              "value": "~*req.Service-Information.IMS-Information.Called-Party-Address",
                              "mandatory": true
                          },
                          {
                              "tag": "AnswerTime",
                              "path": "*cgreq.AnswerTime",
                              "type": "*variable",
                              "value": "~*req.Event-Timestamp",
                              "mandatory": true
                          },
                          {
                              "tag": "Usage",
                              "path": "*cgreq.Usage",
                              "type": "*variable",
                              "value": "~*req.Multiple-Services-Credit-Control.Requested-Service-Unit.CC-Time",
                              "mandatory": true
                          },
                          {
                              "tag": "SubscriberID",
                              "path": "*cgreq.SubscriberId",
                              "type": "*variable",
                              "value": "~*req.Subscription-Id.Subscription-Id-Data",
                              "mandatory": true
                          }
                      ],
                      "reply_fields": [
                          { "tag": "CCATemplate", "type": "*template", "value": "*cca" },
                          {
                              "tag": "GrantedUnits",
                              "path": "*rep.Multiple-Services-Credit-Control.Granted-Service-Unit.CC-Time",
                              "type": "*constant",
                              "value": "30",
                              "mandatory": true
                          },
                          {
                              "tag": "FinalUnitAction",
                              "path": "*rep.Multiple-Services-Credit-Control.Final-Unit-Indication.Final-Unit-Action",
                              "type": "*constant",
                              "value": "1", // REDIRECT
                              "mandatory": true
                          },
                          {
                              "tag": "FinalUnitAction",
                              "path": "*rep.Multiple-Services-Credit-Control.Final-Unit-Indication.Redirect-Server.Redirect-Address-Type",
                              "type": "*constant",
                              "value": "3", // SIP URI
                              "mandatory": true
                          },
                          {
                              "tag": "FinalUnitAction",
                              "path": "*rep.Multiple-Services-Credit-Control.Final-Unit-Indication.Redirect-Server.Redirect-Server-Address",
                              "type": "*constant",
                              "value": "sip://ocs",
                              "mandatory": true
                          },
                      ]
                  },
              ]
          }
      }

