services:
  hss:
    command: /opt/bin/open5gs-hssd -c /etc/hss/open5gs.yaml -t
    configs:
    - source: hss
      target: /etc/hss/open5gs.yaml
    - source: hss.diameter
      target: /etc/hss/diameter.conf
    volumes:
    - certificate:/var/hss
    expose:
    - 3868/tcp
    depends_on:
      certificate:
        condition: service_completed_successfully
      subscribers:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile_inline: |
        FROM alpine AS build
        RUN apk add alpine-sdk bison flex git cmake meson bash sudo linux-headers bsd-compat-headers yaml-dev lksctp-tools-dev gnutls-dev libgcrypt-dev libidn-dev mongo-c-driver-dev libmicrohttpd-dev curl-dev nghttp2-dev talloc-dev
        RUN git clone --depth=1 https://github.com/open5gs/open5gs
        WORKDIR open5gs
        RUN meson build --prefix=/opt
        RUN ninja -C build install

        FROM alpine
        RUN apk add yaml lksctp-tools gnutls libgcrypt libidn mongo-c-driver libmicrohttpd curl nghttp2 talloc
        COPY --from=build /opt /opt

  certificate:
    command: openssl req -new -batch -x509 -days 3650 -nodes -newkey rsa:1024 -out crt.pem -keyout key.pem -subj /CN=hss.epc.${REALM}
    working_dir: /var/hss
    volumes:
    - certificate:/var/hss
    build:
      context: .
      dockerfile_inline: |
        FROM alpine
        RUN apk add openssl

  subscribers:
    image: mongo:8.0
    entrypoint: mongosh --host mongo --file /opt/subscribers.js
    configs:
    - source: subscribers
      target: /opt/subscribers.js
    tmpfs:
    - /data/configdb
    - /data/db
    depends_on:
      mongo:
        condition: service_started
    restart: on-failure

  ui:
    profiles:
    - ui
    working_dir: /open5gs/webui
    command: npm run dev
    environment:
      DB_URI: mongodb://mongo/open5gs
      HOSTNAME: 0.0.0.0
    ports:
    - 9999:9999
    depends_on:
      subscribers:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile_inline: |
        FROM alpine AS build
        RUN apk add git
        RUN git clone https://github.com/open5gs/open5gs

        FROM alpine
        RUN apk add nodejs npm
        COPY --from=build /open5gs/webui /open5gs/webui
        RUN cd /open5gs/webui && npm ci

  mongo:
    image: mongo:8.0
    command: --bind_ip 0.0.0.0
    tmpfs:
    - /data/configdb
    - /data/db
    expose:
    - 27017/udp
    - 27017/tcp


configs:
  hss:
    content: |
      db_uri: mongodb://mongo/open5gs
      hss:
        freeDiameter: /etc/hss/diameter.conf
          #identity: hss.epc.${REALM}
          #load_extension:
          #- module: /opt/lib/freeDiameter/dbg_msg_dumps.fdx
          #  conf: 0x4444
          #- module: /opt/lib/freeDiameter/dict_rfc5777.fdx
          #- module: /opt/lib/freeDiameter/dict_mip6i.fdx
          #- module: /opt/lib/freeDiameter/dict_nasreq.fdx
          #- module: /opt/lib/freeDiameter/dict_nas_mipv6.fdx
          #- module: /opt/lib/freeDiameter/dict_dcca.fdx
          #- module: /opt/lib/freeDiameter/dict_dcca_3gpp.fdx
      logger:
        file:
          path: /var/log/hss.log
      global:
        max:
          ue: 1024

  hss.diameter:
    content: |
      Identity = "hss.epc.${REALM}";
      No_SCTP;
      TLS_Cred = "/var/hss/crt.pem", "/var/hss/key.pem";
      TLS_CA = "/var/hss/crt.pem";

      LoadExtension = "/opt/lib/freeDiameter/dbg_msg_dumps.fdx" : "0x4444";
      LoadExtension = "/opt/lib/freeDiameter/dict_rfc5777.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_mip6i.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_nasreq.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_nas_mipv6.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_dcca.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_dcca_3gpp.fdx";

      ConnectPeer = "icscf.ims.${REALM}" { No_TLS; };
      ConnectPeer = "scscf.ims.${REALM}" { No_TLS; };

  subscribers:
    content: |
      db = db.getSiblingDB('open5gs')
      for(i = 0; i <= 9; i++){
        db.subscribers.insertOne(
        {
            _id: new ObjectId(),
            schema_version: NumberInt(1),
            imsi: `${IMSI}$${i}`,
            msisdn: [`${MSISDN}$${i}`],
            imeisv: [],
            mme_host: [],
            mm_realm: [],
            purge_flag: [],
            slice:[
            {
                sst: NumberInt(1),
                default_indicator: true,
                session: [
                {
                    name : 'internet',
                    type : NumberInt(3),
                    qos : {
                        index: NumberInt(9),
                        arp: {
                            priority_level : NumberInt(8),
                            pre_emption_capability: NumberInt(1),
                            pre_emption_vulnerability: NumberInt(2)
                        }
                    },
                    ambr: {
                        downlink: { value: NumberInt(1000000000), unit: NumberInt(0) },
                        uplink: { value: NumberInt(1000000000), unit: NumberInt(0) }
                    },
                    pcc_rule: [],
                    _id: new ObjectId(),
                }],
                _id: new ObjectId(),
            }],
            security:
            {
                k : '${K}',
                op : null,
                opc : '${OPC}',
                amf : '8000',
            },
            ambr :
            {
                downlink : { value: NumberInt(1000000000), unit: NumberInt(0)},
                uplink : { value: NumberInt(1000000000), unit: NumberInt(0)}
            },
            access_restriction_data: 32,
            network_access_mode: 0,
            subscriber_status: 0,
            operator_determined_barring: 0,
            subscribed_rau_tau_timer: 12,
            __v: 0
        })
      }


volumes:
  certificate:
