services:
  dra:
    image: ghcr.io/lyatanski/freediameter
    configs:
    - source: dra.conf
      target: /etc/freeDiameter/dra.conf
    volumes:
    - cert-dra:/var/dra
    expose:
    - 3868/tcp
    depends_on:
      cert-dra:
        condition: service_completed_successfully

  cert-dra:
    image: ghcr.io/lyatanski/openssl
    command: req -new -batch -x509 -days 3650 -nodes -newkey rsa:1024 -out crt.pem -keyout key.pem -subj /CN=dra.epc
    working_dir: /var/dra
    volumes:
    - cert-dra:/var/dra

  hss:
    image: ghcr.io/lyatanski/open5gs
    command: /opt/bin/open5gs-hssd -c /etc/hss/open5gs.yaml -t
    configs:
    - source: hss.yaml
      target: /etc/hss/open5gs.yaml
    - source: hss.diameter
      target: /etc/hss/diameter.conf
    volumes:
    - cert-hss:/var/hss
    expose:
    - 3868/tcp
    depends_on:
      cert-hss:
        condition: service_completed_successfully
      subscribers:
        condition: service_completed_successfully

  cert-hss:
    image: ghcr.io/lyatanski/openssl
    command: req -new -batch -x509 -days 3650 -nodes -newkey rsa:1024 -out crt.pem -keyout key.pem -subj /CN=hss.epc.${REALM}
    working_dir: /var/hss
    volumes:
    - cert-hss:/var/hss

  subscribers:
    image: mongo:8.0
    entrypoint: mongosh --host mongo --file /opt/subscribers.js
    configs:
    - source: subscribers
      target: /opt/subscribers.js
    tmpfs:
    - /data/configdb
    - /data/db
    depends_on:
      mongo:
        condition: service_started
    restart: on-failure

  ui:
    profiles:
    - ui
    working_dir: /open5gs/webui
    command: npm run dev
    environment:
      DB_URI: mongodb://mongo/open5gs
      HOSTNAME: 0.0.0.0
    ports:
    - 9999:9999
    depends_on:
      subscribers:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile_inline: |
        FROM alpine AS build
        RUN apk add git
        RUN git clone https://github.com/open5gs/open5gs

        FROM alpine
        RUN apk add nodejs npm
        COPY --from=build /open5gs/webui /open5gs/webui
        RUN cd /open5gs/webui && npm ci

  pcrf:
    image: ghcr.io/lyatanski/open5gs
    command: /opt/bin/open5gs-pcrfd -c /etc/pcrf/open5gs.yaml -t
    configs:
    - source: pcrf.yaml
      target: /etc/pcrf/open5gs.yaml
    - source: pcrf.diameter
      target: /etc/pcrf/diameter.conf
    volumes:
    - cert-pcrf:/var/pcrf
    expose:
    - 3868/tcp
    depends_on:
      cert-pcrf:
        condition: service_completed_successfully

  cert-pcrf:
    image: ghcr.io/lyatanski/openssl
    command: req -new -batch -x509 -days 3650 -nodes -newkey rsa:1024 -out crt.pem -keyout key.pem -subj /CN=pcrf.epc.${REALM}
    working_dir: /var/pcrf
    volumes:
    - cert-pcrf:/var/pcrf

  smf:
    image: ghcr.io/lyatanski/open5gs
    command: /opt/bin/open5gs-smfd -c /etc/smf/open5gs.yaml -t
    configs:
    - source: smf.yaml
      target: /etc/smf/open5gs.yaml
    - source: smf.diameter
      target: /etc/smf/diameter.conf
    volumes:
    - cert-smf:/var/smf
    expose:
    - 3868/tcp
    depends_on:
      cert-smf:
        condition: service_completed_successfully
      upf:
        condition: service_started
      pcrf:
        condition: service_started

  cert-smf:
    image: ghcr.io/lyatanski/openssl
    command: req -new -batch -x509 -days 3650 -nodes -newkey rsa:1024 -out crt.pem -keyout key.pem -subj /CN=smf.epc.${REALM}
    working_dir: /var/smf
    volumes:
    - cert-smf:/var/smf

  upf:
    image: ghcr.io/lyatanski/open5gs
    command: /opt/bin/open5gs-upfd -c /etc/upf/open5gs.yaml -t
    configs:
    - source: upf.yaml
      target: /etc/upf/open5gs.yaml
    expose:
    - 8805/udp
    - 2152/udp
    devices:
    - /dev/net/tun
    cap_add:
    - NET_ADMIN
    restart: unless-stopped

  upftun:
    image: alpine
    command:
    - sh
    - -c
    - |
      sleep 3
      ip addr add ${UEGW}/16 dev tunue;
      ip link set tunue up
    network_mode: service:upf
    cap_add:
    - NET_ADMIN
    restart: on-failure

  mongo:
    image: mongo:8.0
    command: --bind_ip 0.0.0.0
    tmpfs:
    - /data/configdb
    - /data/db
    expose:
    - 27017/udp
    - 27017/tcp


configs:
  dra.conf:
    content: |
      Identity = "dra.epc";
      No_SCTP;
      TLS_Cred = "/var/dra/crt.pem", "/var/dra/key.pem";
      TLS_CA = "/var/dra/crt.pem";

      LoadExtension = "dbg_msg_dumps.fdx" : "0x8888";
      ConnectPeer = "hss.epc.${REALM}" { No_TLS; };


  hss.yaml:
    content: |
      db_uri: mongodb://mongo/open5gs
      hss:
        freeDiameter: /etc/hss/diameter.conf
          #identity: hss.epc.${REALM}
          #load_extension:
          #- module: /opt/lib/freeDiameter/dbg_msg_dumps.fdx
          #  conf: 0x4444
          #- module: /opt/lib/freeDiameter/dict_rfc5777.fdx
          #- module: /opt/lib/freeDiameter/dict_mip6i.fdx
          #- module: /opt/lib/freeDiameter/dict_nasreq.fdx
          #- module: /opt/lib/freeDiameter/dict_nas_mipv6.fdx
          #- module: /opt/lib/freeDiameter/dict_dcca.fdx
          #- module: /opt/lib/freeDiameter/dict_dcca_3gpp.fdx
        metrics:
          server:
          - address: 0.0.0.0
            port: 9090
        sms_over_ims: "sip:smsc.epc.${REALM}"
      logger:
        file:
          path: /var/log/hss.log
      global:
        max:
          ue: 1024

  hss.diameter:
    content: |
      Identity = "hss.epc.${REALM}";
      No_SCTP;
      TLS_Cred = "/var/hss/crt.pem", "/var/hss/key.pem";
      TLS_CA = "/var/hss/crt.pem";

      LoadExtension = "/opt/lib/freeDiameter/dbg_msg_dumps.fdx" : "0x4444";
      LoadExtension = "/opt/lib/freeDiameter/dict_rfc5777.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_mip6i.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_nasreq.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_nas_mipv6.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_dcca.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_dcca_3gpp.fdx";

      ConnectPeer = "icscf.ims.${REALM}" { No_TLS; };
      ConnectPeer = "scscf.ims.${REALM}" { No_TLS; };

  pcrf.yaml:
    content: |
      logger:
        file:
          path: /var/log/pcrf.log
      global:
        max:
          ue: 1024
      pcrf:
        freeDiameter: /etc/pcrf/diameter.conf
        metrics:
          server:
          - address: 0.0.0.0
            port: 9090
        session:
        - name: internet
          type: 3  # 1:IPv4, 2:IPv6, 3:IPv4v6
          ambr:
            downlink:
              value: 1
              unit: 3  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
            uplink:
              value: 1
              unit: 3
          qos:
            index: 9
            arp:
              priority_level: 8
              pre_emption_vulnerability: 1  # 1: Disabled, 2:Enabled
              pre_emption_capability: 1  # 1: Disabled, 2:Enabled
        - name: ims
          type: 3  # 1:IPv4, 2:IPv6, 3:IPv4v6
          ambr:
            downlink:
              value: 1
              unit: 3  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
            uplink:
              value: 1
              unit: 3  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
          qos:
            index: 5
            arp:
              priority_level: 1
              pre_emption_vulnerability: 1  # 1: Disabled, 2:Enabled
              pre_emption_capability: 1  # 1: Disabled, 2:Enabled
          pcc_rule:
          - qos:
              index: 1
              arp:
                priority_level: 1
                pre_emption_vulnerability: 1   # 1: Disabled, 2:Enabled
                pre_emption_capability: 1   # 1: Disabled, 2:Enabled
              mbr:
                downlink:
                  value: 82
                  unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
                uplink:
                  value: 82
                  unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
              gbr:
                downlink:
                  value: 82
                  unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
                uplink:
                  value: 82
                  unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
            flow:
            - direction: 2
              description: "permit out icmp from any to assigned"
            - direction: 1
              description: "permit out icmp from any to assigned"
            - direction: 2
              description: "permit out udp from 10.200.136.98/32 23455 to assigned 1-65535"
            - direction: 1
              description: "permit out udp from 10.200.136.98/32 1-65535 to assigned 50021"
          - qos:
              index: 2
              arp:
                priority_level: 4
                pre_emption_vulnerability: 2   # 1: Disabled, 2:Enabled
                pre_emption_capability: 2   # 1: Disabled, 2:Enabled
              mbr:
                downlink:
                  value: 802
                  unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
                uplink:
                  value: 802
                  unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
              gbr:
                downlink:
                  value: 802
                  unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
                uplink:
                  value: 802
                  unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps

  pcrf.diameter:
    content: |
      Identity = "pcrf.epc.${REALM}";
      No_SCTP;
      TLS_Cred = "/var/pcrf/crt.pem", "/var/pcrf/key.pem";
      TLS_CA = "/var/pcrf/crt.pem";

      LoadExtension = "/opt/lib/freeDiameter/dbg_msg_dumps.fdx" : "0x4444";
      LoadExtension = "/opt/lib/freeDiameter/dict_rfc5777.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_mip6i.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_nasreq.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_nas_mipv6.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_dcca.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_dcca_3gpp.fdx";

      ConnectPeer = "pcscf.ims.${REALM}" { No_TLS; };
      ConnectPeer = "smf.epc.${REALM}" { No_TLS; };

  smf.yaml:
    content: |
      logger:
        file:
          path: /var/log/smf.log
      global:
        max:
          ue: 1024
      smf:
        freeDiameter: /etc/smf/diameter.conf
        metrics:
          server:
          - address: 0.0.0.0
            port: 9091
        pfcp:
          server:
          - address: 0.0.0.0
          client:
            upf:
            - address: upf
        gtpc:
          server:
          - address: 0.0.0.0
        gtpu:
          server:
          - address: 0.0.0.0
            advertise: upf
        session:
        - subnet: ${UENET}
          gateway: ${UEGW}
          dnn: ims
        dns:
        - ${DNSv4}
        p-cscf:
        - ${IPSEC}

  smf.diameter:
    content: |
      Identity = "smf.epc.${REALM}";
      No_SCTP;
      TLS_Cred = "/var/smf/crt.pem", "/var/smf/key.pem";
      TLS_CA = "/var/smf/crt.pem";

      LoadExtension = "/opt/lib/freeDiameter/dbg_msg_dumps.fdx" : "0x4444";
      LoadExtension = "/opt/lib/freeDiameter/dict_rfc5777.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_mip6i.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_nasreq.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_nas_mipv6.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_dcca.fdx";
      LoadExtension = "/opt/lib/freeDiameter/dict_dcca_3gpp.fdx";

      ConnectPeer = "pcrf.epc.${REALM}" { ConnectTo = "pcrf"; No_TLS; };

  upf.yaml:
    content: |
      logger:
        file:
          path: /var/log/upf.log
      global:
        max:
          ue: 1024
      upf:
        metrics:
          server:
          - address: 0.0.0.0
            port: 9091
        pfcp:
          server:
          - address: 0.0.0.0
          client:
            smf:
            - address: smf
        gtpu:
          server:
          - address: 0.0.0.0
            advertise: upf
        session:
        - subnet: ${UENET}
          gateway: ${UEGW}
          dnn: ims
          dev: tunue

  subscribers:
    content: |
      db = db.getSiblingDB('open5gs')
      for(i = 1; i <= ${SCALE}; i++){
        db.subscribers.insertOne(
        {
            _id: new ObjectId(),
            schema_version: NumberInt(1),
            imsi: '${MCC}${MNC}'+'000000000000000'.substring('${MCC}${MNC}'.length+`$${i}`.length)+`$${i}`,
            msisdn: ['${DIAL}'+'000000000'.substring(`$${i}`.length)+`$${i}`],
            imeisv: [],
            mme_host: [],
            mm_realm: [],
            purge_flag: [],
            slice:[
            {
                sst: NumberInt(1),
                default_indicator: true,
                session: [
                {
                    name : 'internet',
                    type : NumberInt(3),
                    qos : {
                        index: NumberInt(9),
                        arp: {
                            priority_level : NumberInt(8),
                            pre_emption_capability: NumberInt(1),
                            pre_emption_vulnerability: NumberInt(2)
                        }
                    },
                    ambr: {
                        downlink: { value: NumberInt(1000000000), unit: NumberInt(0) },
                        uplink: { value: NumberInt(1000000000), unit: NumberInt(0) }
                    },
                    pcc_rule: [],
                    _id: new ObjectId(),
                }],
                _id: new ObjectId(),
            }],
            security:
            {
                k : '${K}',
                op : null,
                opc : '${OPC}',
                amf : '8000',
            },
            ambr :
            {
                downlink : { value: NumberInt(1000000000), unit: NumberInt(0)},
                uplink : { value: NumberInt(1000000000), unit: NumberInt(0)}
            },
            access_restriction_data: 32,
            network_access_mode: 0,
            subscriber_status: 0,
            operator_determined_barring: 0,
            subscribed_rau_tau_timer: 12,
            __v: 0
        })
      }


volumes:
  cert-dra:
  cert-hss:
  cert-pcrf:
  cert-smf:
