apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cscf
  labels:
    {{- include "ims.labels" . | nindent 4 }}
data:
  proxy.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <DiameterPeer
        FQDN="pcscf.ims"
        Realm="ims"
        Vendor_Id="10415"
        Product_Name="PCSCF"
        Workers="1"
    >
            <Peer FQDN="ims-dra" Realm="ims" port="3868"/>
            <Auth id="16777236" vendor="10415"/> <!-- Rx 3GPP -->
            <SupportedVendor vendor="10415" />
            <DefaultRoute FQDN="ims-dra" metric="1"/>
    </DiameterPeer>

  interrogating.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <DiameterPeer
        FQDN="icscf.ims"
        Realm="ims"
        Vendor_Id="10415"
        Product_Name="ICSCF"
        Workers="1"
    >
            <Peer FQDN="ims-dra" Realm="ims" port="3868"/>
            <Auth id="16777216" vendor="10415"/> <!-- Cx 3GPP -->
            <SupportedVendor vendor="10415" />
            <DefaultRoute FQDN="ims-dra" metric="1"/>
    </DiameterPeer>

  serving.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <DiameterPeer
        FQDN="scscf.ims"
        Realm="ims"
        Vendor_Id="10415"
        Product_Name="SCSCF"
        Workers="1"
    >
            <Peer FQDN="ims-dra" Realm="ims" port="3868"/>
            <Auth id="16777216" vendor="10415"/> <!-- Cx 3GPP -->
            <Auth id="4"        vendor="10415"/> <!-- Ro 3GPP -->
            <SupportedVendor vendor="10415" />
            <DefaultRoute FQDN="ims-dra" metric="1"/>
    </DiameterPeer>
