apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ims.labels" . | nindent 4 }}
data:
  proxy.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <DiameterPeer
        FQDN="pcscf.ims.${REALM}"
        Realm="ims.${REALM}"
        Vendor_Id="10415"
        Product_Name="CDiameterPeer"
        Workers="1"
    >
            <Peer FQDN="pcrf.epc.${REALM}" Realm="epc.${REALM}" port="3868"/>
            <Auth id="16777236" vendor="10415"/> <!-- Rx 3GPP -->
            <SupportedVendor vendor="10415" />
            <DefaultRoute FQDN="pcrf.epc.${REALM}" metric="1"/>
    </DiameterPeer>

  interrogating.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <DiameterPeer
        FQDN="icscf.ims.${REALM}"
        Realm="ims.${REALM}"
        Vendor_Id="10415"
        Product_Name="CDiameterPeer"
        Workers="1"
    >
            <Peer FQDN="hss.epc.${REALM}" Realm="epc.${REALM}" port="3868"/>
            <Auth id="16777216" vendor="10415"/> <!-- Cx 3GPP -->
            <SupportedVendor vendor="10415" />
            <DefaultRoute FQDN="hss.epc.${REALM}" metric="1"/>
    </DiameterPeer>

  serving.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <DiameterPeer
        FQDN="scscf.ims.${REALM}"
        Realm="ims.${REALM}"
        Vendor_Id="10415"
        Product_Name="CDiameterPeer"
        Workers="1"
    >
            <Peer FQDN="hss.epc.${REALM}" Realm="epc.${REALM}" port="3868"/>
            <Peer FQDN="ocs.${REALM}" Realm="${REALM}" port="3868"/>
            <Auth id="16777216" vendor="10415"/> <!-- Cx 3GPP -->
            <Auth id="4"        vendor="10415"/> <!-- Ro 3GPP -->
            <SupportedVendor vendor="10415" />
            <Realm name="${REALM}">
                <Route FQDN="ocs.${REALM}" metric="1"/>
            </Realm>
            <DefaultRoute FQDN="hss.epc.${REALM}" metric="1"/>
    </DiameterPeer>
