logger:
  level: {{ .root.Values.logger.level }}
global:
db_uri: mongodb://{{ .root.Release.Name }}-mongodb/open5gs
hss:
  metrics:
    server:
    - address: 0.0.0.0
      port: {{ .c.ports.metrics.port }}
  freeDiameter: /etc/freeDiameter/diameter.conf
