services:
  ui:
    profiles:
    - ui
    working_dir: /open5gs/webui
    command: npm run dev
    environment:
      DB_URI: mongodb://mongo/open5gs
      HOSTNAME: 0.0.0.0
    ports:
    - 9999:9999
    depends_on:
      subscribers:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile_inline: |
        FROM alpine AS build
        RUN apk add git
        RUN git clone https://github.com/open5gs/open5gs

        FROM alpine
        RUN apk add nodejs npm
        COPY --from=build /open5gs/webui /open5gs/webui
        RUN cd /open5gs/webui && npm ci
