name: charts
on:
  schedule:
  - cron: '0 1 * * SUN'
  push:
permissions: write-all

jobs:
  charts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Lint
      run: |
        helm dependency update charts/core
        helm dependency update charts/rtpengine
        helm dependency update charts/ims
        helm lint charts/core charts/ims

    - name: Package
      run: |
        helm package --dependency-update charts/core
        helm package --dependency-update charts/ims

    - name: Log in
      run: helm registry login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} oci://ghcr.io/

    - name: Publish IMS
      run: helm push ims-*.tgz oci://ghcr.io/${{ github.actor }}

    - name: Publish Open5GS
      run: helm push core-*.tgz oci://ghcr.io/${{ github.actor }}

  test:
    needs:
    - charts
    runs-on: ubuntu-latest

    steps:
    - name: Create KinD Cluster
      uses: helm/kind-action@v1

    - name: Install Open5GS
      run: helm install core oci://ghcr.io/${{ github.actor }}/core

    - name: Install IMS
      run: helm install ims oci://ghcr.io/${{ github.actor }}/ims --wait --timeout 10m

    - name: Test
      run: helm test ims --logs --timeout 10m

    - name: Debug
      if: always()
      run: |
        kubectl get pods,svc
        kubectl describe pod -l app.kubernetes.io/instance=ims
        for d in $(kubectl get deploy -o name); do echo "== $d"; kubectl logs $d --tail=100; done
