name: compose
on:
  push:
  #workflow_run:
  #  workflows:
  #  - images
  #  types:
  #  - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set Up
      run: docker compose --profile test up --detach

    - name: pre check
      run: docker compose --profile test ps --all

    - name: Wait
      run: docker compose --profile test wait test

    - name: Check
      run: docker compose --profile test ps --all

    - name: Logs
      run: docker compose --profile test logs

    - name: Tear Down
      run: docker compose --profile test down --volumes
