name: compose
on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set Up
      run: docker compose up -d

    - name: Wait
      run: sleep 30

    - name: Check
      run: docker compose ps -a

    - name: Logs
      run: docker compose logs

    - name: Tear Down
      run: docker compose down
