name: compose
on:
  workflow_run:
    workflows:
    - images
    types:
    - completed
    branches:
    - *


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set Up
      run: docker compose --profile test up --detach

    - name: Wait
      run: sleep 90

    - name: Check
      run: docker compose --profile test ps --all

    - name: Logs
      run: docker compose --profile test logs

    - name: Tear Down
      run: docker compose --profile test down --volumes
