name: compose
on:
  push:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set Up
      run: docker compose --profile test up -d

    - name: Wait
      run: sleep 90

    - name: Check
      run: docker compose --profile test ps -a

    - name: Logs
      run: docker compose --profile test logs

    - name: Tear Down
      run: docker compose --profile test down
