name: compose
on:
  push:
  #workflow_run:
  #  workflows:
  #  - images
  #  types:
  #  - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: |
        sudo apt update
        sudo apt install -qqy linux-modules-extra-6.11.0-1014-azure

    - name: Set Up
      run: docker compose --profile test up --detach --quiet-pull

    - name: Check
      run: docker compose --profile test ps --all
      if: always()

    - name: Logs
      run: docker compose --profile test logs
      if: always()

    - name: Wait
      run: docker compose --profile test wait test

    - name: Check
      run: docker compose --profile test ps --all

    - name: Logs
      run: docker compose --profile test logs

    - name: Tear Down
      run: docker compose --profile test down --volumes
