name: build
on:
  schedule:
  - cron: '0 1 * * *'
  push:
permissions: write-all

jobs:
  images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - context: kamailio
          image: cscf
        - context: rtpengine
          image: rtpengine

    steps:
    - uses: actions/checkout@v4

    - name: Log In
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build
      run: docker build -t ghcr.io/${{ github.actor }}/${{ matrix.image }} images/${{ matrix.context }}

#    - name: Get Version
#      id: get
#      run: >
#        docker run --rm ghcr.io/${{ github.actor }}/cscf kamailio --version |
#        sed -n "s/: kamailio \([0-9]\+\.[0-9]\+\.[0-9]\+\).*/=\1/p" >>
#        "$GITHUB_OUTPUT"
#
#    - name: Tag
#      run: docker tag ghcr.io/${{ github.actor }}/cscf ghcr.io/${{ github.actor }}/cscf:${{ steps.get.outputs.version }}
#        docker push ghcr.io/${{ github.actor }}/cscf:${{ steps.get.outputs.version }}

    - name: Publish
      run: |
        docker push ghcr.io/${{ github.actor }}/${{ matrix.image }}

