name: build
on:
  push:

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v4

    - name: Set Up
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

