replicaCount: 2

# Each replica owns one valkey database -- `db.offset + <ordinal>`
db:
  offset: 8

# rtpengine log level: 7 is debug, 6 info
logLevel: 6

media:
  portMin: 30000
  portMax: 40000

image:
  repository: ghcr.io/lyatanski/rtpengine
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

podAnnotations: {}

service:
  port: 9910

monitor:
  port: 9090

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

